# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Banner

# Model Form Field configuration
form: $/deividas/announcementbar/models/banner/fields.yaml

# Model Class name
modelClass: Deividas\AnnouncementBar\Models\Banner

# Default redirect location
defaultRedirect: deividas/announcementbar/banners

# Create page
create:
    title: backend::lang.form.create_title
    redirect: deividas/announcementbar/banners/update/:id
    redirectClose: deividas/announcementbar/banners

# Update page
update:
    title: backend::lang.form.update_title
    redirect: deividas/announcementbar/banners
    redirectClose: deividas/announcementbar/banners

# Preview page
preview:
    title: backend::lang.form.preview_title
